### ISSUE TITLE
Support for complex number coefficients

### ISSUE THREAD

**Issue by pjhuxford** [ickk/aberth#3]
Aberth's method also works for polynomials with complex coefficients, but it appears the functions here only allow for polynomials with coefficients that are real floats.

What would it take to generalize the algorithm given here to allow for complex float coefficients?

**Comment by ickk** [comment]
hi @pjhuxford, thanks for your interest in the project!

I pushed a branch [`complex-coefficients`](https://github.com/ickk/aberth/tree/complex-coefficients) which I think includes the minimum needed changes to make this work in principle. You [can see](https://github.com/ickk/aberth/commit/79bc25f8ff191dc7e70e022b11fa8d233af852fa) that supporting complex coefficients is mostly just a matter of changing the type parameters. (I didn't test it, but the implementation otherwise pretty much follows Aberth's original paper)

Adding proper support to the library would need some extra thinking regarding good API. One quick and easy solution would just be to have a duplicate `aberth` function for complex polynomials, but I think there's probably a better solution.

**Comment by pjhuxford** [comment]
Thank you for the quick response!

I think that just having an entirely separate function for complex polynomials would be fine. In fact, I can't think of any other way of doing it that would still be ergonomic for the end user.

Do you think the original `aberth` function for real coefficients should just be a wrapper around the complex coefficient version? My only fear is that this might impact its performance. But it would make this library easier to maintain.

**Comment by ickk** [comment]
I think I figured out a solution to avoid duplicating the interface. I'm not totally happy with it because it requires making a public trait, but it is nice otherwise.

I haven't really benchmarked anything so I'm happy to just use the unified implementation, and can revisit later if there's a need to specialise to squeeze extra perf.

Any feedback/testing for the implementation (#4) is appreciated
